CREATE TABLE IF NOT EXISTS users (
    id VARCHAR(255) NOT NULL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    lastname VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    profile_image TEXT,
    password VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS messages (
    id VARCHAR(255) NOT NULL PRIMARY KEY,
    from_id VARCHAR(255) NOT NULL,
    to_id VARCHAR(255) NOT NULL,
    content VARCHAR(255),
    media VARCHAR(255),
    media_type VARCHAR(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS blocked_users (
    id VARCHAR(255) NOT NULL PRIMARY KEY,
    blocker_user_id VARCHAR(255) NOT NULL,
    blocked_user_id VARCHAR(255) NOT NULL
);